// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lightning-engine/internal/match"
	"lightning-engine/internal/server"
	"lightning-engine/internal/status"
	"lightning-engine/mq"
)

// Injectors from wire.go:

func wireApp(pair []string) (*app, func(), error) {
	statusStatus := status.NewStatus()
	imq := mq.NewYourMq()
	matchPool, err := match.NewMatchPool(statusStatus, pair, imq)
	if err != nil {
		return nil, nil, err
	}
	serverServer := server.NewServer(statusStatus, matchPool)
	sysSignalHandle := status.NewSysSignalHandle(statusStatus)
	mainApp := newApp(statusStatus, serverServer, sysSignalHandle)
	return mainApp, func() {
	}, nil
}
